version: '3.8'
services:
  api:
    image: roddo-backend
    container_name: roddo-backend
    restart: unless-stopped
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3001
      - JWT_PASSWORD=jwt_password
      - DB_PASSWORD=admin
      - DB_USER=admin
      - DB_DB=roddo
      - DB_HOST=roddo-db
      - DB_PORT=5432
      - DB_DIALECT=postgres
    ports:
    - 3001:3001
    cpus: 0.25
    mem_reservation: "64M"
    mem_limit: "128M"

  roddo-db:
    image: postgres:latest
    container_name: roddo-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=roddo
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  roddo-front:
    container_name: roddo-front
    restart: unless-stopped
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_DOMAIN='http://api:'
      - REACT_APP_PORT=3001
      - REACT_APP_API_KEY=1234
    ports:
    - 80:80
    cpus: 0.25
    mem_reservation: "64M"
    mem_limit: "128M"

networks:
  roddo-network:
    driver: bridge