version: '3.8'
services:
  api:
    image: roddo-backend
    container_name: roddo-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - PORT=3001
      - JWT_PASSWORD=jwt_password
      - DB_PASSWORD=admin
      - DB_USER=admin
      - DB_DB=roddo
      - DB_HOST=roddo-db
      - DB_PORT=5432
      - DB_DIALECT=postgres
    ports:
    - 3001:3001
    volumes:
    - .:/home/node/app
    cpus: 0.25
    mem_reservation: "64M"
    mem_limit: "128M"

  roddo-db:
    image: postgres:latest
    container_name: roddo-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=roddo
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

networks:
  roddo-network:
    driver: bridge