FROM node:alpine
LABEL maintainer="Jose Francisco Alvarez Valdez<alvaresvaldes89@gmail.com>"
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package*.json ./
COPY .sequelizerc .
RUN npm install
RUN npm install -g nodemon sequelize-cli
EXPOSE 3001
CMD ["nodemon", "index.js"]